In [3]:
%useLatestDescriptors
%use dataframe
%use datetime

In [4]:
val dfJson = DataFrame.read("backend/src/main/resources/schedule-2026.json")
dfJson

In [5]:
dfJson.distinct {venue}

venue
FRE 117 Lobby
Mission Peak Foyer
Mission Peak
Dumbarton
Humor
Cafeteria
"Meta FRE 117, Fremont"

In [7]:
import kotlinx.datetime.format.Padding
import kotlinx.datetime.format.char
import kotlin.time.Duration

val format = LocalDateTime.Format {
  year()
  char('-')
  monthNumber(padding = Padding.ZERO)
  char('-')
  dayOfMonth()
  char(' ')
  hour(padding = Padding.ZERO)
  char(':')
  minute(padding = Padding.ZERO)
}
dfJson.add("duration") { format.parse(event_end).toInstant(TimeZone.UTC) - format.parse(event_start).toInstant(TimeZone.UTC) }
  .filter { get("duration") as Duration >= 10.minutes }
  .distinctBy { event_start }
  .select { name and event_start  and event_end and "duration" }
  .sortBy { event_start }

name,event_start,event_end,duration
Registration + Badge Pick-up,2026-05-19 08:00,2026-05-19 17:45,9h 45m
Keynote Sessions To Be Announced,2026-05-19 09:00,2026-05-19 09:25,25m
Keynote: The Creator's Curse: Why Met...,2026-05-19 09:25,2026-05-19 09:45,20m
Keynote: Creating a Golden Path for G...,2026-05-19 09:45,2026-05-19 09:55,10m
Keynote Sessions To Be Announced,2026-05-19 09:55,2026-05-19 10:15,20m
Break,2026-05-19 10:15,2026-05-19 10:35,20m
"Big Graphs, Tiny Contexts: Dev Tools ...",2026-05-19 10:35,2026-05-19 11:00,25m
React Server Components Vs. GraphQL -...,2026-05-19 11:10,2026-05-19 11:35,25m
Shopify's Breadth-First Bet: Rethinki...,2026-05-19 11:45,2026-05-19 12:10,25m
GraphQL: The Internal Agentic API - C...,2026-05-19 12:00,2026-05-19 12:10,10m
Lunch,2026-05-19 12:10,2026-05-19 13:25,1h 15m
The State of GraphQL Agent Skills - D...,2026-05-19 13:25,2026-05-19 13:50,25m
Schema Composition Without Federation...,2026-05-19 14:00,2026-05-19 14:10,10m
Making GraphQL Fun for the Backend To...,2026-05-19 14:25,2026-05-19 14:35,10m
Bringing GraphQL Natively To Relation...,2026-05-19 14:35,2026-05-19 15:00,25m
Breaking up With Inputs (Without Brea...,2026-05-19 14:50,2026-05-19 15:00,10m
Connecting LLMs To GraphQL With Schem...,2026-05-19 15:10,2026-05-19 15:35,25m
Break,2026-05-19 15:35,2026-05-19 15:55,20m
Simplifying MCP Tool Sprawl With Grap...,2026-05-19 15:55,2026-05-19 16:20,25m
Shifting Instagram Development Toward...,2026-05-19 16:30,2026-05-19 16:55,25m